### ISSUE TITLE
TypeError: o.controllers is undefined

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#796]
https://sentry.is.canonical.com/canonical/juju-dashboard/issues/13442/?referrer=github_plugin

Juju 3 beta

```
TypeError: o.controllers is undefined
  at addControllerCloudRegion (/static/js/main.068a3fb8.chunk.js:1:12073)
  at createThunkMiddleware/</</< (/static/js/2.e665898e.chunk.js:2:395391)
  at check_auth/</< (/static/js/main.068a3fb8.chunk.js:1:87495)
  at fetchAllModelStatuses/</< (/static/js/main.068a3fb8.chunk.js:1:11898)
```

**Comment by barrymcgee** [comment]
This has been marked as resolved in Sentry due to inactivity https://sentry.is.canonical.com/canonical/juju-dashboard/issues/13442/
